# Уникальный ключ проекта
sonar.projectKey=greenadmin
sonar.projectName=GreenAdmin Dashboard
sonar.projectVersion=1.0.0

# Исходники
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.ts,**/*.test.tsx

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Кодировка
sonar.sourceEncoding=UTF-8
